[versions]
android = "8.9.1"
android_old = "7.2.2"
androidSdk = "13.2.0"
kotlin = "2.1.10"
uiTooling = "1.7.8"
kotlin_old = "1.7.10"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
[libraries]
android-sdk = { module = "org.maplibre.gl:android-sdk", version.ref = "androidSdk" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" , version.ref= "kotlin" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
com_android_application = { id = "com.android.application", version.ref = "android" }
com_android_library = { id = "com.android.library", version.ref = "android" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }